all: KLP_ChooseReferenceFace.rbz
	zip KLP_ChooseReferenceFace_1.0.0.rbz KLP_ChooseReferenceFace.rb KLP_ChooseReferenceFace/*.rb

KLP_ChooseReferenceFace.rbz: KLP_ChooseReferenceFace.rb KLP_ChooseReferenceFace/*.rb
